
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace DataTable
{

public sealed partial class Aircraft : Luban.BeanBase
{
    public Aircraft(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        ThrusterId = (int)_obj.GetValue("ThrusterId");
        WeaponId0 = (int)_obj.GetValue("WeaponId0");
        WeaponId1 = (int)_obj.GetValue("WeaponId1");
        WeaponId2 = (int)_obj.GetValue("WeaponId2");
        ArmorId0 = (int)_obj.GetValue("ArmorId0");
        ArmorId1 = (int)_obj.GetValue("ArmorId1");
        ArmorId2 = (int)_obj.GetValue("ArmorId2");
        DeadEffectId = (int)_obj.GetValue("DeadEffectId");
        DeadSoundId = (int)_obj.GetValue("DeadSoundId");
    }

    public static Aircraft DeserializeAircraft(JToken _buf)
    {
        return new Aircraft(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 推进器编号
    /// </summary>
    public readonly int ThrusterId;
    /// <summary>
    /// 武器编号0
    /// </summary>
    public readonly int WeaponId0;
    /// <summary>
    /// 武器编号1
    /// </summary>
    public readonly int WeaponId1;
    /// <summary>
    /// 武器编号2
    /// </summary>
    public readonly int WeaponId2;
    /// <summary>
    /// 装甲编号0
    /// </summary>
    public readonly int ArmorId0;
    /// <summary>
    /// 装甲编号1
    /// </summary>
    public readonly int ArmorId1;
    /// <summary>
    /// 装甲编号2
    /// </summary>
    public readonly int ArmorId2;
    /// <summary>
    /// 死亡特效编号
    /// </summary>
    public readonly int DeadEffectId;
    /// <summary>
    /// 死亡声音编号
    /// </summary>
    public readonly int DeadSoundId;


    public const int __ID__ = -624194762;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ThrusterId:" + ThrusterId + ","
        + "WeaponId0:" + WeaponId0 + ","
        + "WeaponId1:" + WeaponId1 + ","
        + "WeaponId2:" + WeaponId2 + ","
        + "ArmorId0:" + ArmorId0 + ","
        + "ArmorId1:" + ArmorId1 + ","
        + "ArmorId2:" + ArmorId2 + ","
        + "DeadEffectId:" + DeadEffectId + ","
        + "DeadSoundId:" + DeadSoundId + ","
        + "}";
    }
}
}

