
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace DataTable
{

public sealed partial class Armor : Luban.BeanBase
{
    public Armor(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        MaxHP = (int)_obj.GetValue("MaxHP");
        Defense = (int)_obj.GetValue("Defense");
    }

    public static Armor DeserializeArmor(JToken _buf)
    {
        return new Armor(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最大生命
    /// </summary>
    public readonly int MaxHP;
    /// <summary>
    /// 防御力
    /// </summary>
    public readonly int Defense;


    public const int __ID__ = 63533343;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MaxHP:" + MaxHP + ","
        + "Defense:" + Defense + ","
        + "}";
    }
}
}

