
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace DataTable
{

public sealed partial class PowerUp : Luban.BeanBase
{
    public PowerUp(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        PowerUpType = (int)_obj.GetValue("PowerUpType");
        Duration = (float)_obj.GetValue("Duration");
        Value = (float)_obj.GetValue("Value");
        Speed = (float)_obj.GetValue("Speed");
        SoundId = (int)_obj.GetValue("SoundId");
    }

    public static PowerUp DeserializePowerUp(JToken _buf)
    {
        return new PowerUp(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int PowerUpType;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 值
    /// </summary>
    public readonly float Value;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 声音编号
    /// </summary>
    public readonly int SoundId;


    public const int __ID__ = 1276706400;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "PowerUpType:" + PowerUpType + ","
        + "Duration:" + Duration + ","
        + "Value:" + Value + ","
        + "Speed:" + Speed + ","
        + "SoundId:" + SoundId + ","
        + "}";
    }
}
}

