
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace DataTable
{

public sealed partial class Scene : Luban.BeanBase
{
    public Scene(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        AssetName = (string)_obj.GetValue("AssetName");
        BackgroundMusicId = (int)_obj.GetValue("BackgroundMusicId");
    }

    public static Scene DeserializeScene(JToken _buf)
    {
        return new Scene(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源名称
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// 背景音乐编号
    /// </summary>
    public readonly int BackgroundMusicId;


    public const int __ID__ = 79702124;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AssetName:" + AssetName + ","
        + "BackgroundMusicId:" + BackgroundMusicId + ","
        + "}";
    }
}
}

