
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace DataTable
{
public partial class Tables
{
    public TbAircraft TbAircraft {get; }
    public TbArmor TbArmor {get; }
    public TbAsteroid TbAsteroid {get; }
    public TbEntity TbEntity {get; }
    public TbMusic TbMusic {get; }
    public TbPowerUp TbPowerUp {get; }
    public TbScene TbScene {get; }
    public TbSound TbSound {get; }
    public TbThruster TbThruster {get; }
    public TbUIForm TbUIForm {get; }
    public TbUISound TbUISound {get; }
    public TbWeapon TbWeapon {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbAircraft = new TbAircraft(loader("tbaircraft"));
        TbArmor = new TbArmor(loader("tbarmor"));
        TbAsteroid = new TbAsteroid(loader("tbasteroid"));
        TbEntity = new TbEntity(loader("tbentity"));
        TbMusic = new TbMusic(loader("tbmusic"));
        TbPowerUp = new TbPowerUp(loader("tbpowerup"));
        TbScene = new TbScene(loader("tbscene"));
        TbSound = new TbSound(loader("tbsound"));
        TbThruster = new TbThruster(loader("tbthruster"));
        TbUIForm = new TbUIForm(loader("tbuiform"));
        TbUISound = new TbUISound(loader("tbuisound"));
        TbWeapon = new TbWeapon(loader("tbweapon"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbAircraft.ResolveRef(this);
        TbArmor.ResolveRef(this);
        TbAsteroid.ResolveRef(this);
        TbEntity.ResolveRef(this);
        TbMusic.ResolveRef(this);
        TbPowerUp.ResolveRef(this);
        TbScene.ResolveRef(this);
        TbSound.ResolveRef(this);
        TbThruster.ResolveRef(this);
        TbUIForm.ResolveRef(this);
        TbUISound.ResolveRef(this);
        TbWeapon.ResolveRef(this);
    }
}

}

