
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbAircraft
{
    private readonly System.Collections.Generic.Dictionary<int, Aircraft> _dataMap;
    private readonly System.Collections.Generic.List<Aircraft> _dataList;
    
    public TbAircraft(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Aircraft>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Aircraft>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Aircraft _v;
            _v = global::DataTable.Aircraft.DeserializeAircraft(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Aircraft> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Aircraft> DataList => _dataList;

    public Aircraft GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Aircraft Get(int key) => _dataMap[key];
    public Aircraft this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

