
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbArmor
{
    private readonly System.Collections.Generic.Dictionary<int, Armor> _dataMap;
    private readonly System.Collections.Generic.List<Armor> _dataList;
    
    public TbArmor(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Armor>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Armor>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Armor _v;
            _v = global::DataTable.Armor.DeserializeArmor(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Armor> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Armor> DataList => _dataList;

    public Armor GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Armor Get(int key) => _dataMap[key];
    public Armor this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

