
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbAsteroid
{
    private readonly System.Collections.Generic.Dictionary<int, Asteroid> _dataMap;
    private readonly System.Collections.Generic.List<Asteroid> _dataList;
    
    public TbAsteroid(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Asteroid>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Asteroid>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Asteroid _v;
            _v = global::DataTable.Asteroid.DeserializeAsteroid(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Asteroid> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Asteroid> DataList => _dataList;

    public Asteroid GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Asteroid Get(int key) => _dataMap[key];
    public Asteroid this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

