
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbEntity
{
    private readonly System.Collections.Generic.Dictionary<int, Entity> _dataMap;
    private readonly System.Collections.Generic.List<Entity> _dataList;
    
    public TbEntity(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Entity>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Entity>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Entity _v;
            _v = global::DataTable.Entity.DeserializeEntity(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Entity> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Entity> DataList => _dataList;

    public Entity GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Entity Get(int key) => _dataMap[key];
    public Entity this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

