
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbMusic
{
    private readonly System.Collections.Generic.Dictionary<int, Music> _dataMap;
    private readonly System.Collections.Generic.List<Music> _dataList;
    
    public TbMusic(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Music>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Music>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Music _v;
            _v = global::DataTable.Music.DeserializeMusic(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Music> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Music> DataList => _dataList;

    public Music GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Music Get(int key) => _dataMap[key];
    public Music this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

