
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbPowerUp
{
    private readonly System.Collections.Generic.Dictionary<int, PowerUp> _dataMap;
    private readonly System.Collections.Generic.List<PowerUp> _dataList;
    
    public TbPowerUp(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PowerUp>(_buf.Count);
        _dataList = new System.Collections.Generic.List<PowerUp>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            PowerUp _v;
            _v = global::DataTable.PowerUp.DeserializePowerUp(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, PowerUp> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<PowerUp> DataList => _dataList;

    public PowerUp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PowerUp Get(int key) => _dataMap[key];
    public PowerUp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

