
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbScene
{
    private readonly System.Collections.Generic.Dictionary<int, Scene> _dataMap;
    private readonly System.Collections.Generic.List<Scene> _dataList;
    
    public TbScene(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Scene>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Scene>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Scene _v;
            _v = global::DataTable.Scene.DeserializeScene(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Scene> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Scene> DataList => _dataList;

    public Scene GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Scene Get(int key) => _dataMap[key];
    public Scene this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

