
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbThruster
{
    private readonly System.Collections.Generic.Dictionary<int, Thruster> _dataMap;
    private readonly System.Collections.Generic.List<Thruster> _dataList;
    
    public TbThruster(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Thruster>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Thruster>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Thruster _v;
            _v = global::DataTable.Thruster.DeserializeThruster(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Thruster> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Thruster> DataList => _dataList;

    public Thruster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Thruster Get(int key) => _dataMap[key];
    public Thruster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

