
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbUIForm
{
    private readonly System.Collections.Generic.Dictionary<int, UIForm> _dataMap;
    private readonly System.Collections.Generic.List<UIForm> _dataList;
    
    public TbUIForm(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, UIForm>(_buf.Count);
        _dataList = new System.Collections.Generic.List<UIForm>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            UIForm _v;
            _v = global::DataTable.UIForm.DeserializeUIForm(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, UIForm> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<UIForm> DataList => _dataList;

    public UIForm GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UIForm Get(int key) => _dataMap[key];
    public UIForm this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

