
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace DataTable
{

public partial class TbWeapon
{
    private readonly System.Collections.Generic.Dictionary<int, Weapon> _dataMap;
    private readonly System.Collections.Generic.List<Weapon> _dataList;
    
    public TbWeapon(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Weapon>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Weapon>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Weapon _v;
            _v = global::DataTable.Weapon.DeserializeWeapon(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, Weapon> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Weapon> DataList => _dataList;

    public Weapon GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Weapon Get(int key) => _dataMap[key];
    public Weapon this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

