
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace DataTable
{

public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        Attack = (int)_obj.GetValue("Attack");
        AttackInterval = (float)_obj.GetValue("AttackInterval");
        BulletId = (int)_obj.GetValue("BulletId");
        BulletSpeed = (float)_obj.GetValue("BulletSpeed");
        BulletSoundId = (int)_obj.GetValue("BulletSoundId");
    }

    public static Weapon DeserializeWeapon(JToken _buf)
    {
        return new Weapon(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float AttackInterval;
    /// <summary>
    /// 子弹编号
    /// </summary>
    public readonly int BulletId;
    /// <summary>
    /// 子弹速度
    /// </summary>
    public readonly float BulletSpeed;
    /// <summary>
    /// 子弹声音编号
    /// </summary>
    public readonly int BulletSoundId;


    public const int __ID__ = -1707954628;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Attack:" + Attack + ","
        + "AttackInterval:" + AttackInterval + ","
        + "BulletId:" + BulletId + ","
        + "BulletSpeed:" + BulletSpeed + ","
        + "BulletSoundId:" + BulletSoundId + ","
        + "}";
    }
}
}

